<?php
// $ID$

/**
 *
 *@file
 *Use this module to learn about Drupal's Menu System.
 */

 /**
  *Implementation of hook_menu().
  */
 function menufun_menu() {
  $items['menufun'] =array(
    'title' => 'Greeting',
    'page callback' => 'menufun_hello',
    'page arguments' => array('Jane', 'Doe'),
    'access callback' => TRUE,
    'weight' => 5,
  );
  return $items;
 }
 /**
  *Page callback.
  */
 function menufun_hello($first_name = '', $last_name = '') {
  return t('Hello @first_name @last_name',
           array('@first_name' => $first_name, '@last_name' => $last_name));

}
